# Generated by Django 4.2.5 on 2023-10-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowedbook',
            name='book_image',
        ),
        migrations.RemoveField(
            model_name='borrowedbook',
            name='book_name',
        ),
        migrations.RemoveField(
            model_name='borrowedbook',
            name='borrow_date',
        ),
        migrations.AlterField(
            model_name='borrowedbook',
            name='borrower_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='borrowedbook',
            name='return_date',
            field=models.DateField(),
        ),
    ]
