# Generated by Django 4.2.5 on 2023-10-06 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admins',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='admins',
            name='image',
            field=models.ImageField(blank=True, height_field=200, null=True, upload_to='profile/', width_field=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, height_field=200, null=True, upload_to='profile/', width_field=200),
        ),
    ]
