# Generated by Django 4.2.5 on 2023-10-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_student_borrowed_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admins',
            name='image',
            field=models.ImageField(blank=True, height_field=200, null=True, upload_to='accounts/static/images', width_field=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, height_field=200, null=True, upload_to='accounts/static/images', width_field=200),
        ),
    ]
