# Generated by Django 4.2.5 on 2023-10-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admins',
            name='image',
            field=models.ImageField(default='2.jpg', upload_to='accounts/static/images'),
        ),
    ]
